# WhirlwindTourOfPython
https://www.oreilly.com/programming/free/files/a-whirlwind-tour-of-python.pdf

In [1]:
L = [1, 2, 3]
L.append(100)
print(L)

[1, 2, 3, 100]


In [2]:
# check if a is between 15 and 30
a = 25
15 < a < 30

True

In [3]:
5 // 2

2

In [4]:
2 ** 5

32

Type Name 	Example 	Description
list 	[1, 2, 3] 	Ordered collection
tuple 	(1, 2, 3) 	Immutable ordered collection
dict 	{'a':1, 'b':2, 'c':3} 	Unordered (key,value) mapping
set 	{1, 2, 3} 	Unordered collection of unique values

int, float, complex, bool, str, and so on.  .

In [19]:
L = [2, 3, 5, 7, 11]
print( "L            "       , L      ) 
print( "L[:3]        "       , L[:3]  )    #  first three elements of the list 
print( "L[-3:]       "       , L[-3:]  )   #  last three elements of the list 
print( "L[0:len(L):2]" , L[0:len(L):2])    #  every second element of the list,
print( "L[::2]       "       , L[::2] )    #  equivalent to L[0:len(L):2]
print( "L[::-1]      "       , LL[::-1] )  #  every element (step size one) in reverse order

L             [2, 3, 5, 7, 11]
L[:3]         [2, 3, 5]
L[-3:]        [5, 7, 11]
L[0:len(L):2] [2, 5, 11]
L[::2]        [2, 5, 11]


In [23]:
 # tuples are immutable: this means that once they are created, their size and contents cannot be changed:
t = (1, 2, 3)
print( "t         "       ,t )  #   
print( "t[0]      "       , t[0] )  #  
print( "t[0]      "       , t[0] )  # 

x = 0.125
x.as_integer_ratio()

t          (1, 2, 3)
t[0]       1
t[0]       1


(1, 8)

In [28]:
#dictionaries
numbers = {'one':1, 'two':2, 'three':3}
numbers['one']      #access via key only
numbers['ninety'] = 90
print(numbers)

{'one': 1, 'two': 2, 'three': 3, 'ninety': 90}


In [39]:
#sets - unordered and unique
primes =   {2, 3,   5,    7}
odds =  {1,    3,   5,    7, 9}
even=      {2,   4   , 6}
# union: items appearing in either
primes.union(odds)      # equivalently with a method
primes | odds |even     # with an operator

# intersection: items appearing in both
primes & odds             # with an operator
primes.intersection(odds) # equivalently with a method

# difference: items in primes but not in odds
primes - odds           # with an operator
primes.difference(odds) # equivalently with a method

# symmetric difference: items appearing in only one set
primes ^ odds                     # with an operator
primes.symmetric_difference(odds) # equivalently with a method


{1, 2, 9}

In [52]:
#funczion

def fibonacci(N):
    L = []
    a, b = 0, 1
    while len(L) < N:
   #     a, b    = b,  a + b  #assinged @ same time!! no order issues
        L.append(a+b)     
        b =  a+ b
        a =  b        
        L[len(L)-2] + L[len(L)-1] 
  
    return L

fibonacci(10)


[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [53]:
# Flexible Arguments
# *args       --  "arguments"  single * before a variable means "expand this as a sequence"
# **kwargs    --  "keyword arguments" double ** before a variable means "expand this as a dictionary"
# lambda funtion to sort dicts e.g.

data = [{'first':'Guido', 'last':'Van Rossum', 'YOB':1956},
        {'first':'Grace', 'last':'Hopper',     'YOB':1906},
        {'first':'Alan',  'last':'Turing',     'YOB':1912}]

#sort alphabetically by first name
sorted(data, key=lambda item: item['first'])

In [55]:
L = [2, 4, 6, 8, 10]

for i, val in enumerate(L):
    print(i, val)

0 2
1 4
2 6
3 8
4 10


In [61]:
L = [2, 4, 6, 8, 10]
R = [3, 6, 9, 12, 15]
for lval, rval in zip(L, R):
    print(lval, rval)
    
L = [2, 4, 6, 8, 10]
R = [3, 6, 9, 12, 15]
for lval, rval in enumerate(zip(L, R)):
    print( lval, rval)    

2 3
4 6
6 9
8 12
10 15
0 (2, 3)
1 (4, 6)
2 (6, 9)
3 (8, 12)
4 (10, 15)


In [99]:
import numpy as np
x = np.arange(1, 10)
x ** 2

M = x.reshape((3, 3))
print(M)
print(M.T)
print("matrix mult w (5,6,): ", np.dot(M, [5, 6, 7]))
print("eigenvektor:          ", np.linalg.eigvals(M))
print("M.max(axis=1):        ", M.max(axis=1))
print("M.max(1):             ", M.max(1))      #same thing

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
matrix mult w (5,6,):  [ 38  92 146]
eigenvektor:           [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]
M.max(axis=1):           [3 6 9]
M.max(1):                [3 6 9]


In [98]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

#    isnull(): Generate a boolean mask indicating missing values
#    notnull(): Opposite of isnull()
#    dropna(): Return a filtered version of the data
#    fillna(): Return a copy of the data with missing values filled or imputed

data.fillna(method='bfill')

[0 1 2]
[[0]
 [1]
 [2]]


In [143]:
import pandas as pd
datadf     = pd.DataFrame(data)
datadf     = datadf.append(pd.DataFrame(['a','b', 'c']))
datadf.rename(columns = {"first": "first_name"}, inplace = True)
datadf.first_name.fillna(method='ffill', inplace = True)     
datadf

0     YOB first_name        last
0  NaN  1956.0      Guido  Van Rossum
1  NaN  1906.0      Grace      Hopper
2  NaN  1912.0       Alan      Turing
0    a     NaN       Alan         NaN
1    b     NaN       Alan         NaN
2    c     NaN       Alan         NaN

Empty DataFrame
Columns: []
Index: []

In [89]:
#help
L?
str.*find*?
%lsmagic
%history  -n 1-4        # previous commands





# Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.
# np.sum       	np.nansum 	Compute sum of elements
# np.prod     	np.nanprod 	Compute product of elements
# np.mean     	np.nanmean 	Compute mean of elements
# np.std      	np.nanstd 	Compute standard deviation
# np.var      	np.nanvar 	Compute variance
# np.min      	np.nanmin 	Find minimum value
# np.max      	np.nanmax 	Find maximum value
# np.argmin   	np.nanargmin 	Find index of minimum value
# np.argmax   	np.nanargmax 	Find index of maximum value
# np.median   	np.nanmedian 	Compute median of elements
# np.percentile 	np.nanpercentile 	Compute rank-based statistics of elements
# np.any      	N/A 	Evaluate whether any elements are true
# np.all      	N/A 	Evaluate whether all elements are true

   1:
L = [1, 2, 3]
L.append(100)
print(L)
   2:
# check if a is between 15 and 30
a = 25
15 < a < 30
   3: 5 // 2
   4: 2 ** 5


array([3, 6, 9])

In [88]:
import numpy        as np
np.__version__
np.zeros(10, dtype='int16')

import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x3)
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [ ]:
reshape our x array into a 3x3 array:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A two-dimensional array is one representation of a matrix, and NumPy knows how to efficiently do typical matrix operations. For example, you can compute the transpose using .T:


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

or a matrix-vector product using np.dot:

np.dot(M, [5, 6, 7])

array([ 38,  92, 146])

and even more sophisticated operations like eigenvalue decomposition:

np.linalg.eigvals(M)

array([  1.61168440e+01,  -1.11684397e+00,  -1.30367773e-15])

